trigger:
- main

pool:
  name: GovardhanPool

steps:
- task: TerraformInstaller@1
  inputs:
    terraformVersion: '1.5.7'

- task: AzureCLI@2
  inputs:
    azureSubscription: 'bankinginfraconnection'   # service connection you created
    scriptType: 'ps'
    scriptLocation: 'inlineScript'
    inlineScript: |
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |    
      terraform init
      terraform plan -out=tfplan
      terraform apply -auto-approve tfplan
