trigger:
- main

pool:
  name: GovardhanPool

steps:
- task: TerraformInstaller@1
  inputs:
    terraformVersion: '1.5.7'

- task: AzureCLI@2
  displayName: 'Login to Azure'
  inputs:
    azureSubscription: 'bankinginfraconnection'   # service connection you created
    scriptType: 'ps'
    scriptLocation: 'inlineScript'
    inlineScript: |
<<<<<<< HEAD
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |    
=======
      echo "Azure CLI login successful"
      az account show
# Terraform commands
- task: PowerShell@2
  displayName: 'Run Terraform'
  inputs:
    targetType: 'inline'
    script: |
      cd $(System.DefaultWorkingDirectory)/Dev
      
>>>>>>> ca5c935 (Fix AzureCLI inlineScript in pipeline)
      terraform init
      terraform plan -out=tfplan
      terraform apply -auto-approve tfplan
